### ISSUE TITLE
[question] How to update a schema ACL ?

### ISSUE THREAD

**Issue by marcelfalliere** [spacedog-io/spacedog-server#54]
Now with commit [21560b... Schema ACL are not updatable through schema settings anymore](21560b81767c517e3936790b1e7984ebd376e096) there seems to be no way to update ACL for a schema ?

This used to work :
```
HTTP PUT "/1/settings/schema"
{
  "schema": {
    "acl": {
      "someschema": {
        "key": [
          "read_all",
          "search"
        ], ...
      }
    }
  }
}
```

Now the result is 
```
{
  "success": false,
  "status": 400,
  "error": {
    "message": "[schema] settings is not directly updatable"
  }
}
```

so how to update a schema ACL now ?

**Comment by davattias** [comment]
Les acl d'un schema sont à configurer directement dans le schema. Exemple :
https://caredev.spacedog.io/1/schema

**Comment by marcelfalliere** [comment]
Merci pour la réponse, je ferme l'issue.
